create table event (type smallint check (type between 0 and 0), created_at timestamp(6) with time zone, id bigint generated by default as identity, payload varchar(255), sku varchar(255), primary key (id));
create table inventory_item (available integer, id integer generated by default as identity, reserved integer, version bigint, sku varchar(255), primary key (id));
